semantic_layer:
  file_path: "assets/semantic_layer.txt"
  reload_interval: 3600

autogen:
  bi_analyst:
    model: "gpt-3.5-turbo"
    temperature: 0.1
    max_tokens: 2000
    max_turns: 5
    agent_silent: false

data_platform:
  cube_categories:
    - orders
    - products
    - inventory
    - customers
    - marketing
    - delivery
  
  default_search_limit: 50
  
  analysis_hints:
    - "Consider both measures and dimensions for complete analysis"
    - "Check cube relationships when analyzing across data marts"
    - "Use dimension variants to understand possible filter values"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "cube_analyst.log"

performance:
  cache_enabled: true
  cache_size: 1000
  timeout_seconds: 30